//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XboxFullScreenExperienceTool.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XboxFullScreenExperienceTool.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable &amp;&amp; Restore 的當地語系化字串。
        /// </summary>
        internal static string btnDisable_Text {
            get {
                return ResourceManager.GetString("btnDisable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Xbox Full Screen Experience 的當地語系化字串。
        /// </summary>
        internal static string btnEnable_Text {
            get {
                return ResourceManager.GetString("btnEnable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fix Xbox Full Screen Experience 的當地語系化字串。
        /// </summary>
        internal static string btnEnable_Text_Fix {
            get {
                return ResourceManager.GetString("btnEnable_Text_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Application is already running. 的當地語系化字串。
        /// </summary>
        internal static string ErrorAppRunning {
            get {
                return ResourceManager.GetString("ErrorAppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Your Windows build ({0}) is too low. 的當地語系化字串。
        /// </summary>
        internal static string ErrorBuildTooLow {
            get {
                return ResourceManager.GetString("ErrorBuildTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Certificate file &apos;{0}&apos; not found. 的當地語系化字串。
        /// </summary>
        internal static string ErrorCertificateFileNotFound {
            get {
                return ResourceManager.GetString("ErrorCertificateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checking Windows build failed with an unexpected error: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorCheckBuild {
            get {
                return ResourceManager.GetString("ErrorCheckBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred while checking status: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorCheckStatus {
            get {
                return ResourceManager.GetString("ErrorCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Driver files &apos;{0}&apos; or &apos;{1}&apos; not found. 的當地語系化字串。
        /// </summary>
        internal static string ErrorDriverFilesNotFound {
            get {
                return ResourceManager.GetString("ErrorDriverFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error reading version number: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorReadingVersion {
            get {
                return ResourceManager.GetString("ErrorReadingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Failed to read or parse current OS build information (CurrentBuild or UBR) from the registry. 的當地語系化字串。
        /// </summary>
        internal static string ErrorReadRegistry {
            get {
                return ResourceManager.GetString("ErrorReadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to execute restart command: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorRestartFailed {
            get {
                return ResourceManager.GetString("ErrorRestartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error restoring registry: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorRestoringRegistry {
            get {
                return ResourceManager.GetString("ErrorRestoringRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to write to the log file: {0} 的當地語系化字串。
        /// </summary>
        internal static string ErrorWritingLogFile {
            get {
                return ResourceManager.GetString("ErrorWritingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Actions 的當地語系化字串。
        /// </summary>
        internal static string grpActions_Text {
            get {
                return ResourceManager.GetString("grpActions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log 的當地語系化字串。
        /// </summary>
        internal static string grpOutput_Text {
            get {
                return ResourceManager.GetString("grpOutput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screen Dimension Override Method (for non-handheld devices) 的當地語系化字串。
        /// </summary>
        internal static string grpPhysPanel_Text {
            get {
                return ResourceManager.GetString("grpPhysPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred:
        ///{0}
        ///
        ///Please ensure you are running this program with administrator privileges. 的當地語系化字串。
        /// </summary>
        internal static string HandleExceptionMessage {
            get {
                return ResourceManager.GetString("HandleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string HandleExceptionTitle {
            get {
                return ResourceManager.GetString("HandleExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Backing up and setting registry... 的當地語系化字串。
        /// </summary>
        internal static string LogBackupAndSetRegistry {
            get {
                return ResourceManager.GetString("LogBackupAndSetRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Backup file deleted. 的當地語系化字串。
        /// </summary>
        internal static string LogBackupDeleted {
            get {
                return ResourceManager.GetString("LogBackupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Backup file found, proceeding with restore. 的當地語系化字串。
        /// </summary>
        internal static string LogBackupFound {
            get {
                return ResourceManager.GetString("LogBackupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 --- Starting Disable Process --- 的當地語系化字串。
        /// </summary>
        internal static string LogBeginDisable {
            get {
                return ResourceManager.GetString("LogBeginDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 --- Starting Enable Process --- 的當地語系化字串。
        /// </summary>
        internal static string LogBeginEnable {
            get {
                return ResourceManager.GetString("LogBeginEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Certificate installed successfully. 的當地語系化字串。
        /// </summary>
        internal static string LogCertificateInstallSuccess {
            get {
                return ResourceManager.GetString("LogCertificateInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checking if DeviceForm registry value needs to be restored... 的當地語系化字串。
        /// </summary>
        internal static string LogCheckingRegistryRestore {
            get {
                return ResourceManager.GetString("LogCheckingRegistryRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver Mode (PhysPanelDrv) selected... 的當地語系化字串。
        /// </summary>
        internal static string LogChoosingDriverMode {
            get {
                return ResourceManager.GetString("LogChoosingDriverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Task Scheduler Mode (PhysPanelCS) selected... 的當地語系化字串。
        /// </summary>
        internal static string LogChoosingSchedulerMode {
            get {
                return ResourceManager.GetString("LogChoosingSchedulerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Found driver package &apos;{0}&apos;, deleting... 的當地語系化字串。
        /// </summary>
        internal static string LogDeletingDriverPackage {
            get {
                return ResourceManager.GetString("LogDeletingDriverPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleting scheduled task &apos;SetPanelDimensions&apos;... 的當地語系化字串。
        /// </summary>
        internal static string LogDeletingTask {
            get {
                return ResourceManager.GetString("LogDeletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 --- Disable Process Complete --- 的當地語系化字串。
        /// </summary>
        internal static string LogDisableComplete {
            get {
                return ResourceManager.GetString("LogDisableComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Explicitly disabling Feature IDs: {0}... 的當地語系化字串。
        /// </summary>
        internal static string LogDisablingFeatures {
            get {
                return ResourceManager.GetString("LogDisablingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver installation was cancelled by the user or failed. The operation has been aborted. 的當地語系化字串。
        /// </summary>
        internal static string LogDriverInstallCancelled {
            get {
                return ResourceManager.GetString("LogDriverInstallCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver installation command executed. 的當地語系化字串。
        /// </summary>
        internal static string LogDriverInstallCommandExecuted {
            get {
                return ResourceManager.GetString("LogDriverInstallCommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver removal command executed. 的當地語系化字串。
        /// </summary>
        internal static string LogDriverRemoveCommandExecuted {
            get {
                return ResourceManager.GetString("LogDriverRemoveCommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 --- Enable Process Complete --- 的當地語系化字串。
        /// </summary>
        internal static string LogEnableComplete {
            get {
                return ResourceManager.GetString("LogEnableComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabling Feature IDs: {0}... 的當地語系化字串。
        /// </summary>
        internal static string LogEnablingFeatures {
            get {
                return ResourceManager.GetString("LogEnablingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please ensure this program is run with [Administrator Privileges]. 的當地語系化字串。
        /// </summary>
        internal static string LogErrorAdminRights {
            get {
                return ResourceManager.GetString("LogErrorAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver installation failed or was cancelled by the user. (Exit code: {0}) 的當地語系化字串。
        /// </summary>
        internal static string LogErrorDriverInstallCancelled {
            get {
                return ResourceManager.GetString("LogErrorDriverInstallCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver installation failed: {0} 的當地語系化字串。
        /// </summary>
        internal static string LogErrorDriverInstallFailed {
            get {
                return ResourceManager.GetString("LogErrorDriverInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver removal failed: {0} 的當地語系化字串。
        /// </summary>
        internal static string LogErrorDriverRemoveFailed {
            get {
                return ResourceManager.GetString("LogErrorDriverRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to remove the existing driver while switching modes, but will proceed with setting up the new mode. 的當地語系化字串。
        /// </summary>
        internal static string LogErrorDriverRemoveFailedDuringSwitch {
            get {
                return ResourceManager.GetString("LogErrorDriverRemoveFailedDuringSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to remove the driver. Manual cleanup may be required. 的當地語系化字串。
        /// </summary>
        internal static string LogErrorDriverRemoveFailedGeneral {
            get {
                return ResourceManager.GetString("LogErrorDriverRemoveFailedGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: {0} 的當地語系化字串。
        /// </summary>
        internal static string LogErrorPrefix {
            get {
                return ResourceManager.GetString("LogErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read screen dimension, unable to determine if a scheduled task is needed. 的當地語系化字串。
        /// </summary>
        internal static string LogErrorReadingScreenSize {
            get {
                return ResourceManager.GetString("LogErrorReadingScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to read screen dimension, skipping this step. 的當地語系化字串。
        /// </summary>
        internal static string LogErrorReadingScreenSizeEnable {
            get {
                return ResourceManager.GetString("LogErrorReadingScreenSizeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An unexpected error occurred: {0} 的當地語系化字串。
        /// </summary>
        internal static string LogErrorUnexpected {
            get {
                return ResourceManager.GetString("LogErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Features successfully set to disabled state. 的當地語系化字串。
        /// </summary>
        internal static string LogFeaturesDisabledSuccess {
            get {
                return ResourceManager.GetString("LogFeaturesDisabledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Features enabled successfully. 的當地語系化字串。
        /// </summary>
        internal static string LogFeaturesEnabledSuccess {
            get {
                return ResourceManager.GetString("LogFeaturesEnabledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finding driver package (PhysPanelDrv.inf)... 的當地語系化字串。
        /// </summary>
        internal static string LogFindingDriverPackage {
            get {
                return ResourceManager.GetString("LogFindingDriverPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Installing driver certificate... 的當地語系化字串。
        /// </summary>
        internal static string LogInstallingCertificate {
            get {
                return ResourceManager.GetString("LogInstallingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Installing driver using devcon... 的當地語系化字串。
        /// </summary>
        internal static string LogInstallingDriverWithDevcon {
            get {
                return ResourceManager.GetString("LogInstallingDriverWithDevcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LOGGING ERROR 的當地語系化字串。
        /// </summary>
        internal static string LogLoggingErrorPrefix {
            get {
                return ResourceManager.GetString("LogLoggingErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No backup file found, indicating this tool has not modified the registry. No restore needed. 的當地語系化字串。
        /// </summary>
        internal static string LogNoBackupFound {
            get {
                return ResourceManager.GetString("LogNoBackupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation failed, rolling back changes... 的當地語系化字串。
        /// </summary>
        internal static string LogOperationFailedRollingBack {
            get {
                return ResourceManager.GetString("LogOperationFailedRollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reading current screen dimension... 的當地語系化字串。
        /// </summary>
        internal static string LogReadingScreenSize {
            get {
                return ResourceManager.GetString("LogReadingScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Backup file content is invalid. Safely removing registry value &apos;{0}&apos;. 的當地語系化字串。
        /// </summary>
        internal static string LogRegistryBackupInvalid {
            get {
                return ResourceManager.GetString("LogRegistryBackupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original DeviceForm value not found, created restore marker. 的當地語系化字串。
        /// </summary>
        internal static string LogRegistryBackupMarkedForDelete {
            get {
                return ResourceManager.GetString("LogRegistryBackupMarkedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Backed up original DeviceForm value ({0}) to {1}. 的當地語系化字串。
        /// </summary>
        internal static string LogRegistryBackupSuccess {
            get {
                return ResourceManager.GetString("LogRegistryBackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Registry key successfully set to 46 (0x2E). 的當地語系化字串。
        /// </summary>
        internal static string LogRegistrySetSuccess {
            get {
                return ResourceManager.GetString("LogRegistrySetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removed registry value &apos;{0}&apos; based on backup marker. 的當地語系化字串。
        /// </summary>
        internal static string LogRegistryValueRemoved {
            get {
                return ResourceManager.GetString("LogRegistryValueRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restored value from backup: {0} 的當地語系化字串。
        /// </summary>
        internal static string LogRegistryValueRestored {
            get {
                return ResourceManager.GetString("LogRegistryValueRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 False (Not exist) 的當地語系化字串。
        /// </summary>
        internal static string LogRegStatusFalseNotExist {
            get {
                return ResourceManager.GetString("LogRegStatusFalseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 False (Value is {0}) 的當地語系化字串。
        /// </summary>
        internal static string LogRegStatusFalseWrongValue {
            get {
                return ResourceManager.GetString("LogRegStatusFalseWrongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True (Value is 46) 的當地語系化字串。
        /// </summary>
        internal static string LogRegStatusTrue {
            get {
                return ResourceManager.GetString("LogRegStatusTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removing driver device... 的當地語系化字串。
        /// </summary>
        internal static string LogRemovingDriverDevice {
            get {
                return ResourceManager.GetString("LogRemovingDriverDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detected existing driver service, removing it to avoid conflicts... 的當地語系化字串。
        /// </summary>
        internal static string LogRemovingOldDriver {
            get {
                return ResourceManager.GetString("LogRemovingOldDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detected existing scheduled task, removing it to avoid conflicts... 的當地語系化字串。
        /// </summary>
        internal static string LogRemovingOldTask {
            get {
                return ResourceManager.GetString("LogRemovingOldTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removing PhysPanelDrv driver... 的當地語系化字串。
        /// </summary>
        internal static string LogRemovingPhysPanelDrv {
            get {
                return ResourceManager.GetString("LogRemovingPhysPanelDrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rollback complete. No changes were made to the system. 的當地語系化字串。
        /// </summary>
        internal static string LogRollbackComplete {
            get {
                return ResourceManager.GetString("LogRollbackComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully read screen dimension: {0}x{1}mm. 的當地語系化字串。
        /// </summary>
        internal static string LogScreenSizeSuccess {
            get {
                return ResourceManager.GetString("LogScreenSizeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screen dimension ({0:F2}&quot;) is larger than the {1}&quot; threshold, creating startup task... 的當地語系化字串。
        /// </summary>
        internal static string LogScreenSizeTooLarge {
            get {
                return ResourceManager.GetString("LogScreenSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Undefined screen dimension (0x0mm) detected, creating startup task... 的當地語系化字串。
        /// </summary>
        internal static string LogScreenSizeUndefined {
            get {
                return ResourceManager.GetString("LogScreenSizeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status Check -&gt; ViVe Features: {0}, Registry: {1}, Task Required: {2}, Task Exists: {3} 的當地語系化字串。
        /// </summary>
        internal static string LogStatusCheck {
            get {
                return ResourceManager.GetString("LogStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status Check: CoreEnabled={0} (ViVeFeatures={1}, Registry={2}), ScreenOverrideRequired={3}, OverridePresent={4} (CS={5}, Drv={6}), TestSigning={7} 的當地語系化字串。
        /// </summary>
        internal static string LogStatusCheckSummary {
            get {
                return ResourceManager.GetString("LogStatusCheckSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Task &apos;SetPanelDimensions&apos; created. 的當地語系化字串。
        /// </summary>
        internal static string LogTaskCreated {
            get {
                return ResourceManager.GetString("LogTaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scheduled task deleted. 的當地語系化字串。
        /// </summary>
        internal static string LogTaskDeleted {
            get {
                return ResourceManager.GetString("LogTaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screen dimension ({0:F2}&quot;) is within the {1}&quot; range, no task needed. 的當地語系化字串。
        /// </summary>
        internal static string LogTaskNotNeeded {
            get {
                return ResourceManager.GetString("LogTaskNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Test Signing mode is not enabled. PhysPanelDrv option is disabled. 的當地語系化字串。
        /// </summary>
        internal static string LogTestSigningDisabled {
            get {
                return ResourceManager.GetString("LogTestSigningDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User chose to restart later. No further actions can be performed until restart. 的當地語系化字串。
        /// </summary>
        internal static string LogUserRestartLater {
            get {
                return ResourceManager.GetString("LogUserRestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User chose to restart now. 的當地語系化字串。
        /// </summary>
        internal static string LogUserRestartNow {
            get {
                return ResourceManager.GetString("LogUserRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Xbox Full Screen Experience Tool 的當地語系化字串。
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Could not automatically restart. Please restart your computer manually. 的當地語系化字串。
        /// </summary>
        internal static string MessageBoxRestartFailed {
            get {
                return ResourceManager.GetString("MessageBoxRestartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable Success 的當地語系化字串。
        /// </summary>
        internal static string PromptRestartCaptionDisableSuccess {
            get {
                return ResourceManager.GetString("PromptRestartCaptionDisableSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        internal static string PromptRestartCaptionSuccess {
            get {
                return ResourceManager.GetString("PromptRestartCaptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All changes have been applied. A restart is required for them to take full effect.
        ///
        ///Would you like to restart now? 的當地語系化字串。
        /// </summary>
        internal static string PromptRestartMessage {
            get {
                return ResourceManager.GetString("PromptRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PhysPanelCS (Task Scheduler Mode, high security, default option) 的當地語系化字串。
        /// </summary>
        internal static string radPhysPanelCS_Text {
            get {
                return ResourceManager.GetString("radPhysPanelCS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PhysPanelDrv (Driver Mode, high stability, requires Test Signing ON) 的當地語系化字串。
        /// </summary>
        internal static string radPhysPanelDrv_Text {
            get {
                return ResourceManager.GetString("radPhysPanelDrv_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This tool requires build {0} or higher. 的當地語系化字串。
        /// </summary>
        internal static string RequiredBuild {
            get {
                return ResourceManager.GetString("RequiredBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Checking... 的當地語系化字串。
        /// </summary>
        internal static string StatusChecking {
            get {
                return ResourceManager.GetString("StatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Disabled 的當地語系化字串。
        /// </summary>
        internal static string StatusDisabled {
            get {
                return ResourceManager.GetString("StatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver Mode Error: Please Disable to Restore 的當地語系化字串。
        /// </summary>
        internal static string StatusDriverErrorNeedsDisable {
            get {
                return ResourceManager.GetString("StatusDriverErrorNeedsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Enabled 的當地語系化字串。
        /// </summary>
        internal static string StatusEnabled {
            get {
                return ResourceManager.GetString("StatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Enabled (Driver Mode) 的當地語系化字串。
        /// </summary>
        internal static string StatusEnabledDriverMode {
            get {
                return ResourceManager.GetString("StatusEnabledDriverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Enabled (Task Scheduler Mode) 的當地語系化字串。
        /// </summary>
        internal static string StatusEnabledSchedulerMode {
            get {
                return ResourceManager.GetString("StatusEnabledSchedulerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Needs fix (Screen dimension task not set up correctly) 的當地語系化字串。
        /// </summary>
        internal static string StatusNeedsFix {
            get {
                return ResourceManager.GetString("StatusNeedsFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Restart pending... 的當地語系化字串。
        /// </summary>
        internal static string StatusRestartPending {
            get {
                return ResourceManager.GetString("StatusRestartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Unknown (Error) 的當地語系化字串。
        /// </summary>
        internal static string StatusUnknownError {
            get {
                return ResourceManager.GetString("StatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to create scheduled task: {0} 的當地語系化字串。
        /// </summary>
        internal static string TaskSchedulerManagerErrorCreate {
            get {
                return ResourceManager.GetString("TaskSchedulerManagerErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to delete scheduled task: {0} 的當地語系化字串。
        /// </summary>
        internal static string TaskSchedulerManagerErrorDelete {
            get {
                return ResourceManager.GetString("TaskSchedulerManagerErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Could not get the application&apos;s installation directory. 的當地語系化字串。
        /// </summary>
        internal static string TaskSchedulerManagerErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("TaskSchedulerManagerErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Necessary file not found: {0}. Please ensure PhysPanelCS.exe is in the same directory as the main program. 的當地語系化字串。
        /// </summary>
        internal static string TaskSchedulerManagerErrorFindFile {
            get {
                return ResourceManager.GetString("TaskSchedulerManagerErrorFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown Version 的當地語系化字串。
        /// </summary>
        internal static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version Incompatible 的當地語系化字串。
        /// </summary>
        internal static string VersionIncompatible {
            get {
                return ResourceManager.GetString("VersionIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version meets requirements. 的當地語系化字串。
        /// </summary>
        internal static string VersionOK {
            get {
                return ResourceManager.GetString("VersionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning: Corresponding oem&lt;number&gt;.inf file not found, it may have already been removed. 的當地語系化字串。
        /// </summary>
        internal static string WarningOemInfNotFound {
            get {
                return ResourceManager.GetString("WarningOemInfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome to the Xbox Full Screen Experience Tool! 的當地語系化字串。
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Windows build version: {0} 的當地語系化字串。
        /// </summary>
        internal static string YourBuildVersion {
            get {
                return ResourceManager.GetString("YourBuildVersion", resourceCulture);
            }
        }
    }
}
