//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysPanelCS.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhysPanelCS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Commands: 的當地語系化字串。
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current dimensions: {0}x{1}mm ({2:F2}&quot;) 的當地語系化字串。
        /// </summary>
        internal static string CurrentSize {
            get {
                return ResourceManager.GetString("CurrentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PhysPanelCS {0} - Windows Internal Display Physical Size Tool 的當地語系化字串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Could not get display dimensions. 的當地語系化字串。
        /// </summary>
        internal static string ErrorGetFailed {
            get {
                return ResourceManager.GetString("ErrorGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Could not set display dimensions. This operation requires SYSTEM user privileges. 的當地語系化字串。
        /// </summary>
        internal static string ErrorSetFailed {
            get {
                return ResourceManager.GetString("ErrorSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Invalid parameters for &apos;set&apos; command. 的當地語系化字串。
        /// </summary>
        internal static string ErrorSetInvalid {
            get {
                return ResourceManager.GetString("ErrorSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Unknown command &apos;{0}&apos; 的當地語系化字串。
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Examples: 的當地語系化字串。
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   get                      Get the current physical size settings. 的當地語系化字串。
        /// </summary>
        internal static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   PhysPanelCS get 的當地語系化字串。
        /// </summary>
        internal static string GetExample {
            get {
                return ResourceManager.GetString("GetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   set &lt;width&gt; &lt;height&gt;     Set new physical dimensions (in millimeters). 的當地語系化字串。
        /// </summary>
        internal static string SetDescription {
            get {
                return ResourceManager.GetString("SetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   PhysPanelCS set 155 87 的當地語系化字串。
        /// </summary>
        internal static string SetExample {
            get {
                return ResourceManager.GetString("SetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set successfully. 的當地語系化字串。
        /// </summary>
        internal static string SetSuccess {
            get {
                return ResourceManager.GetString("SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown Version 的當地語系化字串。
        /// </summary>
        internal static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Usage: PhysPanelCS &lt;command&gt; [parameters...] 的當地語系化字串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
