blank_issues_enabled: false
contact_links:
  - name: 📖 Read the README
    url: https://github.com/8bit2qubit/XboxFullScreenExperienceTool?tab=readme-ov-file
    about: Please read the README documentation for requirements and setup.